export type RootStackParamList = {
    Login: undefined;
    Register: undefined;
    ForgotPassword: { email?: string };
    VerifyOTP: { email: string };
    ResetPassword: { email: string; otp: string };
    MainTabs: undefined;
    Notifications: undefined;
    InstaHelp: undefined;
    WomensSalon: undefined;
    MensSalon: undefined;
    Cleaning: undefined;
    Electrician: undefined;
    NativeWaterPurifier: undefined;
    Painting: undefined;
    ACRepair: undefined;
    Revamp: undefined;
    NativeSmartHome: undefined;
    SubCategory: { slug: string; name: string; isOthers?: boolean };
    ServiceListing: { slug: string; name: string; isOthers?: boolean };
    ServiceDetail: { item: any };
    VendorSelection: { item: any };
    BookingOverview: { item: any; vendor?: any };
    BookingSchedule: { item: any; vendorId?: string };
    BookingLocation: { item: any; date: string; slot: string; vendorId?: string };
    BookingInstructions: { item: any; date: string; slot: string; location: any; vendorId?: string };
    BookingReview: { item: any; date: string; slot: string; location: any; instructions: string; attachmentUrl?: string; vendorId?: string };
    PersonalInformation: undefined;
    SavedAddresses: undefined;
    AddAddress: undefined;
    PaymentMethods: undefined;
    AddPaymentMethod: undefined;
    PushNotifications: undefined;
    SupportHelp: undefined;
    Topup: undefined;
    WalletHistory: undefined;
    Chat: { bookingId: string; professionalName: string; professionalImage?: string };
    VendorTabs: undefined;
    VendorCreateOffer: undefined;
    BookingDetails: { bookingId: string };
    VendorPersonalInformation: undefined;
    VendorNotificationSettings: undefined;
    VendorSupportHelp: undefined;
    VendorQuestionnaire: undefined;
    // Others category flow screens
    OthersServiceRequest: {
        serviceName: string;
        serviceItemId?: string;
        categoryId?: string;
        categoryName?: string;
        subcategoryId?: string;
        subcategoryName?: string;
    };
    OthersRequestSuccess: { requestId: string };
    MyOthersRequests: undefined;
};

export type TabParamList = {
    Explore: undefined;
    Bookings: undefined;
    Wallet: undefined;
    Profile: undefined;
    Ads: undefined;
};
